steps:
  # Passo 1: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-Image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/assessment-ai-backend:$COMMIT_SHA'
      - '.'

  # Passo 2: Fazer o push da imagem para o Container Registry do GCP
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push-Image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/assessment-ai-backend:$COMMIT_SHA'

  # Passo 3: Fazer o Deploy para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy-Cloud-Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'assessment-ai-backend-git'
      - '--image'
      - 'gcr.io/$PROJECT_ID/assessment-ai-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      # Isso garante que a conexão nativa com o Cloud SQL não se perca no Deploy
      - '--set-cloudsql-instances'
      - 'ipnet-digital-efficiency-dev:us-central1:assessment-maturidade'

# Especificar as imagens que devem ser enviadas ao registry ao final do job
images:
  - 'gcr.io/$PROJECT_ID/assessment-ai-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
